disabledMods = [
    "aether",
    "aether_overworld_ores",
    "another_furniture",
    "artificers_armory",
    "berry_good",
    "block_factorys_bosses",
    "bosses_of_mass_destruction",
    "bountifulfares",
    "buzzier_bees",
    "caverns_and_chasms",
    "clayworks",
    "darkerdepths",
    "deep_aether",
    "enderscape",
    "goodending",
    "irons_spellbooks",
    "minecraft",
    "modtemplate",
    "mowziesmobs",
    "natures_spirit",
    "netherexp",
    "oreganized",
    "perfectparity",
    "primal",
    "quark",
    "revotedwildfire",
    "spawn",
    "structure_crafter",
    "supplementaries",
    "the_beyond",
    "woodworks",
]
